# Generated by Django 2.1.3 on 2018-12-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_url',
            field=models.CharField(default='https://s3-us-west-2.amazonaws.com/myroadmap.io/images/profiles/nobody.jpg', max_length=255),
        ),
    ]
